//go:build ignore

// Generates names.go: one IconName constant per file in svg/.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

func main() {
	entries, err := os.ReadDir("svg")
	if err != nil {
		log.Fatal(err)
	}
	var b bytes.Buffer
	b.WriteString("// Code generated by gen.go; DO NOT EDIT.\n\npackage mdi\n\nconst (\n")
	for _, e := range entries {
		name := strings.TrimSuffix(e.Name(), ".svg")
		ident := "Icon"
		for _, part := range strings.Split(name, "-") {
			ident += strings.ToUpper(part[:1]) + part[1:]
		}
		fmt.Fprintf(&b, "%s IconName = %q\n", ident, name)
	}
	b.WriteString(")\n")
	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("names.go", src, 0644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("names.go: %d constants\n", len(entries))
}
