//go:build ignore

// Generates icons.go (one //go:embed + func pair per file in svg/, so the
// linker dead-code-eliminates icons you never call) and all/all.go (a
// name → constructor registry that pins every icon, for icon browsers).
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

func main() {
	entries, err := os.ReadDir("svg")
	if err != nil {
		log.Fatal(err)
	}

	var icons, all bytes.Buffer
	icons.WriteString(`// Code generated by gen.go; DO NOT EDIT.

package mdi

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

`)
	all.WriteString(`// Code generated by gen.go; DO NOT EDIT.

// Package all registers every MDI icon by name. Importing it pins all
// SVGs into the binary — only use it when you need dynamic lookup.
package all

import (
	"fyne.io/fyne/v2"

	"github.com/roffe/mdi"
)

// Icons maps every MDI icon name to its constructor.
var Icons = map[string]func() fyne.Resource{
`)

	for _, e := range entries {
		name := strings.TrimSuffix(e.Name(), ".svg")
		var suffix string
		for _, part := range strings.Split(name, "-") {
			suffix += strings.ToUpper(part[:1]) + part[1:]
		}
		fmt.Fprintf(&icons, "//go:embed svg/%s\nvar svg%s []byte\n\n// Icon%s returns the %q MDI icon.\nfunc Icon%s() fyne.Resource { return res(%q, svg%s) }\n\n",
			e.Name(), suffix, suffix, name, suffix, e.Name(), suffix)
		fmt.Fprintf(&all, "%q: mdi.Icon%s,\n", name, suffix)
	}
	all.WriteString("}\n")

	write("icons.go", icons.Bytes())
	if err := os.MkdirAll("all", 0755); err != nil {
		log.Fatal(err)
	}
	write("all/all.go", all.Bytes())
	fmt.Printf("icons.go + all/all.go: %d icons\n", len(entries))
}

func write(path string, b []byte) {
	src, err := format.Source(b)
	if err != nil {
		log.Fatalf("%s: %v", path, err)
	}
	if err := os.WriteFile(path, src, 0644); err != nil {
		log.Fatal(err)
	}
}
